---
project_name: hcl2json
builds:
  - main: main.go
    binary: hcl2json
    ldflags:
      - -s -w
        -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: binary
    files:
      - none*
    replacements:
      linux: Linux
      darwin: Darwin
      386: i386
      amd64: x86_64
release:
  github:
    owner: Bonial-International-GmbH
    name: hcl2json
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
